### ISSUE TITLE
cursor is jumping after the first key press

### ISSUE THREAD

**Issue by andreivladmatei** [bsorrentino/swiftui-fieldvalidator#1]
GREAT library, but:

There is a problem with the cursor, after the first character is typed. 

See attached video for the following example:

`@Binding var item: Item`
`@State private var nameValid = FieldChecker()`

```
TextFieldWithValidator(
    title: "e.g. Joe's lager",
    value: self.$item.item.name,
    checker: $nameValid,
    onCommit: submit) { v in 

    if v.isEmpty  {
        return "name cannot be empty"
    }

    return nil
}
```
See below gif: I tried to input "Name" and i got "AmeN"

![ScreenRecording2020-01-25at11223](https://user-images.githubusercontent.com/19395668/73119116-e1c12600-3f65-11ea-95f0-e4e57927a252.gif)

**Comment by andreivladmatei** [comment]
[cursor_defect_on_example.patch.zip](https://github.com/bsorrentino/swiftui-fieldvalidator/files/4112052/cursor_defect_on_example.patch.zip)

managed to reproduce it with your example

**Comment by bsorrentino** [comment]
hi @andreimateiro 

Thanks for feedback, I'll check soon

**Comment by bsorrentino** [comment]
hi @andreimateiro 

the problem is related to your code because in SwiftUI to manage binding over struct/class you have to inherit from `ObservableObject` and use `@Published` property wrapper.

So, if you update `DataItem2` struct from

```swift
struct DataItem2  {
    var username: String = ""
}
```

to 

```swift
class DataItem2 : ObservableObject {
    @Published  var username: String = ""
}
```

**all works as expected**

I've pushed a new branch  [feature/issue#1](https://github.com/bsorrentino/swiftui-fieldvalidator/tree/feature/issue%231) with the working sample

**Comment by andreivladmatei** [comment]
@bsorrentino, the problem of class vs struct resides on complex objects annotated with @State. Those will not refresh the ui if for example InstanceA.person.name if modified in a subview (binding).

Using observable/published over all DTOs will pollute all the code :/

**Comment by bsorrentino** [comment]
@andreimateiro 

Understand your point but using `@State` with struct members seems that update events are raised in wrong way

It is not something that I can address in my library ... this is more a matter of what  SwiftUI/Combine suggest as a solution to handle this situation.

I'll try to figure out  if there is a technique to solve this
