### ISSUE TITLE
Modifying state during view update, this will cause undefined behavior.

### ISSUE THREAD

**Issue by chitvanMM** [bsorrentino/swiftui-fieldvalidator#2]
PFA
![Screenshot 2021-08-27 at 3 10 13 PM](https://user-images.githubusercontent.com/85546174/131107489-0f3e50ea-a76b-4809-b353-4901c12c26e7.png)

**Comment by bsorrentino** [comment]
Hi @chitvanMM, thanks for feedback 

Currently i work on `Xcode Version 12.5.1 (12E507)` but I haven't any notification (like you) of such warning

**Comment by chitvanMM** [comment]
In Xcode 13 beta I see this alert as soon as i run the app. In 12.5.1 I saw these warnings on and off sometimes but were not consistent.

**Comment by bsorrentino** [comment]
I think that will be enough force running of  such  code in UI thread  using `DispatchQueue.main.async { }`

Currently i'm working on `debounce` implementation ( issue #3 ) that will solve this problem

**Comment by bsorrentino** [comment]
fix release in `1.4.0` version
