### ISSUE TITLE
Use with ViewModels

### ISSUE THREAD

**Issue by JulesMoorhouse** [bsorrentino/swiftui-fieldvalidator#4]
Hi,

I'd really like to be able to use this with a view model.

So I'd like to abstract the validation out of the view.

I'm thinking a view modifier might be helpful.

I've spent sometime on a different validator package and had problems.
I just wondered if you've had any reports of issues or believe this approach might not work ?

I'd be grateful if you could point me any example you may have.

Thanks,

Jules.

**Comment by bsorrentino** [comment]
Hi @JulesMoorhouse  

Please could you give me more details ? 

What do you does mean for "_I'd really like to be able to use this with a view model._" ?

**Comment by JulesMoorhouse** [comment]
Thanks for your reply @bsorrentino 

Like this…

```
import CoreData
import Foundation
import ValidatedPropertyKit

extension EditView {
    class ViewModel: NSObject, ObservableObject {
        let item: Item
        let add: Bool
        let hasRelationship: Bool

        private let dataController: DataController

        @Published var title: String
```

**Comment by bsorrentino** [comment]
In my example I've used a  [Model](https://github.com/bsorrentino/swiftui-fieldvalidator/raw/master/Example/FieldValidatorSample/ContentView.swift). Where are the differences respect  approach that you wish ?

**Comment by JulesMoorhouse** [comment]
@bsorrentino i was hoping to put most of the validation functionality in my view model, with it being more data related and less about layout.

**Comment by bsorrentino** [comment]
@JulesMoorhouse  finally I got your point. 

Taking in consideration that the validation logic is inside “_validation closure_", you could move such closure within model (you could do also for `FieldChecker2` )

Hope this help to keep your design more generic

**Comment by bsorrentino** [comment]
@JulesMoorhouse you could also create specific `Binding` extensions like:

```swift
extension Binding where Value : Hashable {

    public func validateUsername( _ checker:FieldChecker2<Value>) -> Binding<Value> {
        return onValidate( checker: checker ) {
              // username  validation closure
        }
   }

    public func validateMail( _ checker:FieldChecker2<Value>) -> Binding<Value> {
        return onValidate( checker: checker ) {
              // mail  validation closure
        }
   }
}

```

what do you think ?

**Comment by JulesMoorhouse** [comment]
That looks interesting @bsorrentino although I'm not sure how I'd use it ?

**Comment by JulesMoorhouse** [comment]
I've made some progress.

However, for some reason the validation is a character behind.
I tried to mock up what I have in the sample app and the same issue occurs...

Any ideas, see attached
[FormWithValidatorV1_5.swift.txt](https://github.com/bsorrentino/swiftui-fieldvalidator/files/7875806/FormWithValidatorV1_5.swift.txt)

**Comment by bsorrentino** [comment]
@JulesMoorhouse  I've deployed a working sample [here](https://github.com/bsorrentino/swiftui-fieldvalidator/blob/develop/Example/FieldValidatorSample/FormWithValidator_Issue4.swift)
